## 3.Pandas

### 3.1 Pandas基本介绍

Python Data Analysis Library或pandas是基于Numpy的一种工具，该工具是为了解决数据分析任务而创建的。Pandas纳入了大量库和一些标准的数据模型，提供了高效地操作大型数据集所需要的工具。pandas提供了大量能使我们快速便捷的处理数据的函数和方法。

In [1]:
import pandas as pd
import numpy as np

#### 3.1.1 Pandas的基本数据结构

pandas中有两种常用的基本结构

•Series<br>
    一维数组，与Numpy中的一维array类似，二者与Python基本的数据结构List也很相似。Series能保存同种数据类型，字符串、boolean值、数字等都能保存在Series中。

•DataFrame<br>
二维的表格型数据结构，很多功能与R种的data.frame类似。可以将DataFrame理解为Series的容器。

##### 3.1.1.1 Pandas库的Series类型

一维Series可以用一维列表初始化

In [2]:
a=pd.Series([1,3,5,np.nan,6,5])
print(a)

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    5.0
dtype: float64

默认的情况下，Series的下标都是数字（可以使用额外参数指定），类型是统一的。

In [3]:
b=pd.Series([1,3,5,np.nan,6,5],index=['a','b','c','d','e','f'])
print(b)

a    1.0
b    3.0
c    5.0
d    NaN
e    6.0
f    5.0
dtype: float64

索引——数据行标签

In [4]:
a.index

RangeIndex(start=0, stop=6, step=1)

In [5]:
b.index

Index(['a', 'b', 'c', 'd', 'e', 'f'], dtype='object')

取值

In [6]:
a.values

array([ 1.,  3.,  5., nan,  6.,  5.])

In [7]:
a[0]

1.0

In [11]:
b[1]

3.0

In [12]:
b["b"]

3.0

切片

In [8]:
a[2:5]

2    5.0
3    NaN
4    6.0
dtype: float64

In [9]:
b['b':'f':2]

b    3.0
d    NaN
f    5.0
dtype: float64

索引赋值

In [13]:
a.index.name='索引'
a

索引
0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    5.0
dtype: float64

In [14]:
a.index=list('abcdef')
a

a    1.0
b    3.0
c    5.0
d    NaN
e    6.0
f    5.0
dtype: float64

##### 3.1.1.2 Pandas库的DataFrame类型

###### DataFrame初始化

DataFrame是个二维结构，这里首先构造一组时间序列，作为第一维的下标

In [15]:
date=pd.date_range('20200101',periods=6)
print(date)

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')

然后创建一个DataFream结构

In [21]:
df=pd.DataFrame(np.random.randn(6,4))
df    ##默认使用0、1、2.。。作为索引index

          0         1         2         3
0 -1.490125  1.298987 -0.543361  1.221980
1 -0.849709  0.118608 -0.955715  0.144980
2 -0.599598 -0.756037 -1.795249 -0.282495
3 -0.332586  1.750622 -1.493345 -2.100013
4 -0.905893 -0.254791 -1.476728 -0.001651
5 -1.121065 -1.861881 -0.502420  0.523135

In [16]:
df=pd.DataFrame(np.random.randn(6,4),index=date,columns=list('ABCD'))
df    ##index参数设置行索引，columns参数设置列索引

                   A         B         C         D
2020-01-01 -0.451651 -0.239800 -1.485379 -0.257016
2020-01-02  1.009597  0.223012  0.793047 -0.201220
2020-01-03  1.795496  1.218378  0.091191  1.583309
2020-01-04  1.242861 -0.928178  1.306285  0.465929
2020-01-05  0.675201 -0.747530  0.760223 -0.472335
2020-01-06 -1.252007 -0.814752 -0.266401  1.134847

除了向DataFrame中传入二维数组，我们也可以使用字典传入数据

In [17]:
df1=pd.DataFrame({
    'A':1,
    'B':pd.Timestamp('20200101'),
    'C':pd.Series(1,index=list(range(4)),dtype=float),
    'D':np.array([3]*4,dtype=int),
    'E':pd.Categorical(['test','train','test','train']),
    'F':'abc'})
df1

   A          B    C  D      E    F
0  1 2020-01-01  1.0  3   test  abc
1  1 2020-01-01  1.0  3  train  abc
2  1 2020-01-01  1.0  3   test  abc
3  1 2020-01-01  1.0  3  train  abc

字典的每个key代表一列，其value可以是各种能够转化为Series的对象<br>
与Series要求所有的类型都一致不同，DataFrame只要求每一列数据的格式相同

In [18]:
df1.dtypes

A             int64
B    datetime64[ns]
C           float64
D             int32
E          category
F            object
dtype: object

###### DataFrame查看数据

头尾数据<br>
head和tail方法可以分别查看最前面几行和最后面几行的数据（默认为5）

In [19]:
df.head()

                   A         B         C         D
2020-01-01 -0.451651 -0.239800 -1.485379 -0.257016
2020-01-02  1.009597  0.223012  0.793047 -0.201220
2020-01-03  1.795496  1.218378  0.091191  1.583309
2020-01-04  1.242861 -0.928178  1.306285  0.465929
2020-01-05  0.675201 -0.747530  0.760223 -0.472335

In [20]:
df.tail(3)

                   A         B         C         D
2020-01-04  1.242861 -0.928178  1.306285  0.465929
2020-01-05  0.675201 -0.747530  0.760223 -0.472335
2020-01-06 -1.252007 -0.814752 -0.266401  1.134847

下标、列标、数据

下标使用index属性查看

In [21]:
df.index

DatetimeIndex(['2020-01-01', '2020-01-02', '2020-01-03', '2020-01-04',
               '2020-01-05', '2020-01-06'],
              dtype='datetime64[ns]', freq='D')

列标使用columns属性查看

In [22]:
df.columns

Index(['A', 'B', 'C', 'D'], dtype='object')

数据值使用values查看

In [23]:
df.values

array([[-0.45165137, -0.23979978, -1.48537947, -0.25701596],
       [ 1.00959698,  0.22301238,  0.79304726, -0.20121966],
       [ 1.7954964 ,  1.21837831,  0.09119086,  1.58330876],
       [ 1.24286089, -0.92817811,  1.3062851 ,  0.46592909],
       [ 0.67520128, -0.74752961,  0.76022308, -0.47233524],
       [-1.25200652, -0.81475213, -0.26640107,  1.13484742]])

#### 3.1.2 Pandas读取数据及数据操作

我们以豆瓣的电影数据作为我们深入了解Pandas的示例

In [24]:
df_mv=pd.read_excel(r'F:\ztj\Python\jupyter-notebook\b站学习数据分析\课程中用到的数据\豆瓣电影数据.xlsx')
df_mv.head()

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
0,肖申克的救赎,692795.0,剧情/犯罪,美国,1994-09-10 00:00:00,142,1994,9.6,多伦多电影节
1,控方证人,42995.0,剧情/悬疑/犯罪,美国,1957-12-17 00:00:00,116,1957,9.5,美国
2,美丽人生,327855.0,剧情/喜剧/爱情,意大利,1997-12-20 00:00:00,116,1997,9.5,意大利
3,阿甘正传,580897.0,剧情/爱情,美国,1994-06-23 00:00:00,142,1994,9.4,洛杉矶首映
4,霸王别姬,478523.0,剧情/爱情/同性,中国大陆,1993-01-01 00:00:00,171,1993,9.4,香港

##### 行操作

**iloc为位置索引**

In [28]:
df_mv.iloc[0]

名字                   肖申克的救赎
投票人数               692795.0
类型                    剧情/犯罪
产地                       美国
上映时间    1994-09-10 00:00:00
时长                      142
年代                     1994
评分                      9.6
首映地点                 多伦多电影节
Name: 0, dtype: object

In [29]:
df_mv.iloc[0:5]

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
序号,,,,,,,,,
0,肖申克的救赎,692795.0,剧情/犯罪,美国,1994-09-10 00:00:00,142,1994,9.6,多伦多电影节
1,控方证人,42995.0,剧情/悬疑/犯罪,美国,1957-12-17 00:00:00,116,1957,9.5,美国
2,美丽人生,327855.0,剧情/喜剧/爱情,意大利,1997-12-20 00:00:00,116,1997,9.5,意大利
3,阿甘正传,580897.0,剧情/爱情,美国,1994-06-23 00:00:00,142,1994,9.4,洛杉矶首映
4,霸王别姬,478523.0,剧情/爱情/同性,中国大陆,1993-01-01 00:00:00,171,1993,9.4,香港

**也可以使用 loc, 普通索引**

In [31]:
df_mv.loc[0:5]

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
序号,,,,,,,,,
0,肖申克的救赎,692795.0,剧情/犯罪,美国,1994-09-10 00:00:00,142,1994,9.6,多伦多电影节
1,控方证人,42995.0,剧情/悬疑/犯罪,美国,1957-12-17 00:00:00,116,1957,9.5,美国
2,美丽人生,327855.0,剧情/喜剧/爱情,意大利,1997-12-20 00:00:00,116,1997,9.5,意大利
3,阿甘正传,580897.0,剧情/爱情,美国,1994-06-23 00:00:00,142,1994,9.4,洛杉矶首映
4,霸王别姬,478523.0,剧情/爱情/同性,中国大陆,1993-01-01 00:00:00,171,1993,9.4,香港
5,泰坦尼克号,157074.0,剧情/爱情/灾难,美国,2012-04-10 00:00:00,194,2012,9.4,中国大陆

##### 添加一行

In [32]:
dit={'名字':'复仇者联盟3',
     '投票人数':123456,
     '类型':'剧情/科幻',
     '产地':'美国',
     '上映时间':'2017-05-04 00:00:00',
     '时长':142,
     '年代':2017,
     '评分':8.7,
     '首映地点':'美国'}
s=pd.Series(dit)
s.name=38738
s

名字                   复仇者联盟3
投票人数                 123456
类型                    剧情/科幻
产地                       美国
上映时间    2017-05-04 00:00:00
时长                      142
年代                     2017
评分                      8.7
首映地点                     美国
Name: 38738, dtype: object

In [42]:
df_mv=df_mv.append(s)
df_mv.tail()

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点,序号
序号,,,,,,,,,,
38734,1935年,57.0,喜剧/歌舞,美国,1935-03-15 00:00:00,98,1935,7.6,美国,38735.0
38735,血溅画屏,95.0,剧情/悬疑/犯罪/武侠/古装,中国大陆,1905-06-08 00:00:00,91,1986,7.1,美国,38736.0
38736,魔窟中的幻想,51.0,惊悚/恐怖/儿童,中国大陆,1905-06-08 00:00:00,78,1986,8.0,美国,38737.0
38737,列宁格勒围困之星火战役 Блокада: Фильм 2: Ленинградский ме...,32.0,剧情/战争,苏联,1905-05-30 00:00:00,97,1977,6.6,美国,38738.0
38738,复仇者联盟3,123456.0,剧情/科幻,美国,2017-05-04 00:00:00,142,2017,8.7,美国,NaN

##### 删除一行

In [43]:
df_mv=df_mv.drop([38738])
df_mv.tail()

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点,序号
序号,,,,,,,,,,
38733,神学院 S,46.0,Adult,法国,1905-06-05 00:00:00,58,1983,8.6,美国,38734.0
38734,1935年,57.0,喜剧/歌舞,美国,1935-03-15 00:00:00,98,1935,7.6,美国,38735.0
38735,血溅画屏,95.0,剧情/悬疑/犯罪/武侠/古装,中国大陆,1905-06-08 00:00:00,91,1986,7.1,美国,38736.0
38736,魔窟中的幻想,51.0,惊悚/恐怖/儿童,中国大陆,1905-06-08 00:00:00,78,1986,8.0,美国,38737.0
38737,列宁格勒围困之星火战役 Блокада: Фильм 2: Ленинградский ме...,32.0,剧情/战争,苏联,1905-05-30 00:00:00,97,1977,6.6,美国,38738.0

##### 列操作

In [35]:
df_mv.columns

Index(['名字', '投票人数', '类型', '产地', '上映时间', '时长', '年代', '评分', '首映地点'], dtype='object')

In [38]:
df_mv['名字'].iloc[0:5]

序号
0    肖申克的救赎
1      控方证人
2     美丽人生
3      阿甘正传
4      霸王别姬
Name: 名字, dtype: object

In [39]:
df_mv["名字"][0:5]

序号
0    肖申克的救赎
1      控方证人
2     美丽人生
3      阿甘正传
4      霸王别姬
Name: 名字, dtype: object

In [40]:
df_mv[['名字','类型']][:5]

        名字        类型
序号
0   肖申克的救赎     剧情/犯罪
1     控方证人  剧情/悬疑/犯罪
2    美丽人生   剧情/喜剧/爱情
3     阿甘正传     剧情/爱情
4     霸王别姬  剧情/爱情/同性

##### 增加一列

In [41]:
df_mv['序号']=range(1,len(df_mv)+1)
df_mv.head()

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点,序号
序号,,,,,,,,,,
0,肖申克的救赎,692795.0,剧情/犯罪,美国,1994-09-10 00:00:00,142,1994,9.6,多伦多电影节,1
1,控方证人,42995.0,剧情/悬疑/犯罪,美国,1957-12-17 00:00:00,116,1957,9.5,美国,2
2,美丽人生,327855.0,剧情/喜剧/爱情,意大利,1997-12-20 00:00:00,116,1997,9.5,意大利,3
3,阿甘正传,580897.0,剧情/爱情,美国,1994-06-23 00:00:00,142,1994,9.4,洛杉矶首映,4
4,霸王别姬,478523.0,剧情/爱情/同性,中国大陆,1993-01-01 00:00:00,171,1993,9.4,香港,5

##### 删除一列

In [68]:
df_mv=df_mv.drop('序号',axis=1)
df_mv.head()

,Unnamed: 0,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
0,0.0,肖申克的救赎,692795.0,剧情/犯罪,美国,1994-09-10 00:00:00,142,1994,9.6,多伦多电影节
1,1.0,控方证人,42995.0,剧情/悬疑/犯罪,美国,1957-12-17 00:00:00,116,1957,9.5,美国
2,2.0,美丽人生,327855.0,剧情/喜剧/爱情,意大利,1997-12-20 00:00:00,116,1997,9.5,意大利
3,3.0,阿甘正传,580897.0,剧情/爱情,美国,1994-06-23 00:00:00,142,1994,9.4,洛杉矶首映
4,4.0,霸王别姬,478523.0,剧情/爱情/同性,中国大陆,1993-01-01 00:00:00,171,1993,9.4,香港

##### 通过标签选择数据<br>
**df.loc[[index],[column]]**通过标签选择数据

In [73]:
df_mv.loc[[1,3,4],['名字','评分']]

     名字   评分
1  控方证人  9.5
3  阿甘正传  9.4
4  霸王别姬  9.4

In [47]:
df_mv.loc[1,'名字']

'控方证人'

**df.iloc[[index],[column]]**通过位置选择数据

In [46]:
df_mv.iloc[1:2,0:2]

      名字     投票人数
序号
1   控方证人  42995.0

##### 条件选择

选取产地为美国的所有电影

In [77]:
df_mv[df_mv['产地']=='中国大陆'][:5]

,Unnamed: 0,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
4,4.0,霸王别姬,478523.0,剧情/爱情/同性,中国大陆,1993-01-01 00:00:00,171,1993,9.4,香港
21,21.0,大闹天宫,74881.0,动画/奇幻,中国大陆,1905-05-14 00:00:00,114,1961,9.2,上集
29,29.0,穹顶之下,51113.0,纪录片,中国大陆,2015-02-28 00:00:00,104,2015,9.2,中国大陆
38,38.0,茶馆,10678.0,剧情/历史,中国大陆,1905-06-04 00:00:00,118,1982,9.2,美国
45,45.0,山水情,10781.0,动画/短片,中国大陆,1905-06-10 00:00:00,19,1988,9.2,美国

选取产地为美国，且评分大于9的电影

In [81]:
df_mv[(df_mv.产地=='美国')&(df_mv.评分>9)].head()

,Unnamed: 0,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
0,0.0,肖申克的救赎,692795.0,剧情/犯罪,美国,1994-09-10 00:00:00,142,1994,9.6,多伦多电影节
1,1.0,控方证人,42995.0,剧情/悬疑/犯罪,美国,1957-12-17 00:00:00,116,1957,9.5,美国
3,3.0,阿甘正传,580897.0,剧情/爱情,美国,1994-06-23 00:00:00,142,1994,9.4,洛杉矶首映
5,5.0,泰坦尼克号,157074.0,剧情/爱情/灾难,美国,2012-04-10 00:00:00,194,2012,9.4,中国大陆
6,6.0,辛德勒的名单,306904.0,剧情/历史/战争,美国,1993-11-30 00:00:00,195,1993,9.4,华盛顿首映

选取产地为美国或中国大陆，且评分大于9的电影

In [48]:
df_mv[((df_mv.产地=='美国')|(df_mv.产地=='中国大陆'))&(df_mv.评分>9)].head()

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点,序号
序号,,,,,,,,,,
0,肖申克的救赎,692795.0,剧情/犯罪,美国,1994-09-10 00:00:00,142,1994,9.6,多伦多电影节,1.0
1,控方证人,42995.0,剧情/悬疑/犯罪,美国,1957-12-17 00:00:00,116,1957,9.5,美国,2.0
3,阿甘正传,580897.0,剧情/爱情,美国,1994-06-23 00:00:00,142,1994,9.4,洛杉矶首映,4.0
4,霸王别姬,478523.0,剧情/爱情/同性,中国大陆,1993-01-01 00:00:00,171,1993,9.4,香港,5.0
5,泰坦尼克号,157074.0,剧情/爱情/灾难,美国,2012-04-10 00:00:00,194,2012,9.4,中国大陆,6.0

#### 3.1.3 数据清洗

##### 缺失值处理

dropna：根据标签中的缺失值进行过滤，删除缺失值<br>
fillna：对缺失值进行填充<br>
isnull：返回一个布尔值对象，判断哪些值是缺失值<br>
notnull：isnull的否定式

###### 判断缺失值

In [49]:
df_mv[df_mv['名字'].isnull()].head()

      名字    投票人数      类型  产地                 上映时间   时长    年代   评分 首映地点     序号
序号
231  NaN   144.0  纪录片/音乐  韩国  2011-02-02 00:00:00   90  2011  9.7   美国  232.0
361  NaN    80.0      短片  其他  1905-05-17 00:00:00    4  1964  5.7   美国  362.0
369  NaN  5315.0      剧情  日本  2004-07-10 00:00:00  111  2004  7.5   日本  370.0
372  NaN   263.0   短片/音乐  英国  1998-06-30 00:00:00   34  1998  9.2   美国  373.0
374  NaN    47.0      短片  其他  1905-05-17 00:00:00    3  1964  6.7   美国  375.0

###### 填充缺失值

填充字符类

In [50]:
df_mv[df_mv['名字'].isnull()].head()

      名字    投票人数      类型  产地                 上映时间   时长    年代   评分 首映地点     序号
序号
231  NaN   144.0  纪录片/音乐  韩国  2011-02-02 00:00:00   90  2011  9.7   美国  232.0
361  NaN    80.0      短片  其他  1905-05-17 00:00:00    4  1964  5.7   美国  362.0
369  NaN  5315.0      剧情  日本  2004-07-10 00:00:00  111  2004  7.5   日本  370.0
372  NaN   263.0   短片/音乐  英国  1998-06-30 00:00:00   34  1998  9.2   美国  373.0
374  NaN    47.0      短片  其他  1905-05-17 00:00:00    3  1964  6.7   美国  375.0

In [51]:
df_mv['名字'].fillna('未知电影',inplace=True)
df_mv[df_mv['名字'].isnull()].head()

Empty DataFrame
Columns: [名字, 投票人数, 类型, 产地, 上映时间, 时长, 年代, 评分, 首映地点, 序号]
Index: []

填充数值类

In [52]:
##添加一行，用于实验。此处设置评分为空nan
dit={'名字':'复仇者联盟3',
     '投票人数':123456,
     '类型':'剧情/科幻',
     '产地':'美国',
     '上映时间':'2017-05-04 00:00:00',
     '时长':142,
     '年代':2017,
     '评分':np.nan,
     '首映地点':'美国'}
s=pd.Series(dit)
s.name=38738
df_mv=df_mv.append(s)

In [53]:
##判断“评分”为空的
df_mv[df_mv['评分'].isnull()].head()

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点,序号
序号,,,,,,,,,,
38738,复仇者联盟3,123456.0,剧情/科幻,美国,2017-05-04 00:00:00,142,2017,NaN,美国,NaN

In [54]:
##填充评分，此处填充 均值
df_mv['评分'].fillna(np.mean(df_mv['评分']),inplace=True)
df_mv[-1:]

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点,序号
序号,,,,,,,,,,
38738,复仇者联盟3,123456.0,剧情/科幻,美国,2017-05-04 00:00:00,142,2017,6.935704,美国,NaN

###### 删除缺失值<br>
df.dropna(参数)<br><br>
subset=['列名']：删除该列为空的行<br>
how='all'：删除全为空值的行或列<br>
inplace=True：覆盖之前的数据<br>
axis=0：选择行或列（=0，删除一行；=1，删除一列），默认为0

In [55]:
len(df_mv)

38739

In [56]:
df_mv1=df_mv.dropna()
len(df_mv1)

38735

##### 异常值处理

异常值，即在数据集中存在不合理的值，又称离群点。比如年龄为-1，笔记本电脑重量为1吨等等，都属与异常值的范围。

对于异常值，一般来说数量都会很少，在不影响整体数据分布的情况下，我们直接删除就可以了。

In [112]:
df_mv[(df_mv.投票人数<0)|(df_mv['投票人数']%1!=0)]

,Unnamed: 0,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
19777,19777.0,皇家大贼 皇家大,-80.00,剧情/犯罪,中国香港,1985-05-31 00:00:00,60,1985,6.3,美国
19786,19786.0,日本的垃圾去中国大陆 にっぽんの“ゴミ” 大陆へ渡る ～中国式リサイクル錬,-80.00,纪录片,日本,1905-06-26 00:00:00,60,2004,7.9,美国
19791,19791.0,女教师 女教,8.30,剧情/犯罪,日本,1977-10-29 00:00:00,100,1977,6.6,日本
19797,19797.0,女教徒,-118.00,剧情,法国,1966-05-06 00:00:00,135,1966,7.8,美国
19804,19804.0,女郎漫游仙境 ドレミファ娘の血は騒,5.90,喜剧/歌舞,日本,1985-11-03 00:00:00,80,1985,6.7,日本
19820,19820.0,女仆日记,12.87,剧情,法国,2015-04-01 00:00:00,96,2015,5.7,法国
38055,38055.0,逃出亚卡拉,12.87,剧情/动作/惊悚/犯罪,美国,1979-09-20 00:00:00,112,1979,7.8,美国

#### 3.1.4 数据保存

数据处理之后，然后将数据重新保存到原文件

In [57]:
df_mv.to_excel('movie_data.xlsx')

### 3.2 Pandas操作

In [58]:
import pandas as pd
import numpy as np

以豆瓣电影为例

In [59]:
df=pd.read_excel(r'F:\ztj\Python\jupyter-notebook\b站学习数据分析\课程中用到的数据\豆瓣电影数据.xlsx')
df.head()

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
0,肖申克的救赎,692795.0,剧情/犯罪,美国,1994-09-10 00:00:00,142,1994,9.6,多伦多电影节
1,控方证人,42995.0,剧情/悬疑/犯罪,美国,1957-12-17 00:00:00,116,1957,9.5,美国
2,美丽人生,327855.0,剧情/喜剧/爱情,意大利,1997-12-20 00:00:00,116,1997,9.5,意大利
3,阿甘正传,580897.0,剧情/爱情,美国,1994-06-23 00:00:00,142,1994,9.4,洛杉矶首映
4,霸王别姬,478523.0,剧情/爱情/同性,中国大陆,1993-01-01 00:00:00,171,1993,9.4,香港

In [60]:
df.dtypes

名字       object
投票人数    float64
类型       object
产地       object
上映时间     object
时长       object
年代       object
评分      float64
首映地点     object
dtype: object

#### 3.2.1 数据格式转换

查看格式

In [20]:
df['投票人数'].dtype

dtype('float64')

格式转化

In [61]:
df['投票人数']=df['投票人数'].astype('int')
df['投票人数'].dtype

dtype('int32')

将年代格式转化为整型

In [62]:
df['年代'].dtype

dtype('O')

In [63]:
df['年代']=df['年代'].astype('int')

ValueError: invalid literal for int() with base 10: '2008\u200e'

In [64]:
##年代中有异常值 '2008\u200e'，无法正常转化
df[df.年代=='2008\u200e']

         名字  投票人数  类型    产地                 上映时间  时长     年代   评分 首映地点
15205  狂蟒惊魂   544  恐怖  中国大陆  2008-04-08 00:00:00  93  2008‎  2.7   美国

In [65]:
df[df.年代=='2008\u200e']['年代'].values

array(['2008\u200e'], dtype=object)

In [66]:
df.loc[15205,'年代']=2008
df.loc[15205]

名字                     狂蟒惊魂
投票人数                    544
类型                       恐怖
产地                     中国大陆
上映时间    2008-04-08 00:00:00
时长                       93
年代                     2008
评分                      2.7
首映地点                     美国
Name: 15205, dtype: object

In [80]:
df['年代']=df['年代'].astype('int')
df['年代'][:5]

0    1994
1    1957
2    1997
3    1994
4    1993
Name: 年代, dtype: int32

将时长转化为整数格式

In [67]:
df['时长']=df['时长'].astype('int')

ValueError: invalid literal for int() with base 10: '8U'

In [68]:
df[df.时长=='8U']

             名字  投票人数      类型  产地                 上映时间  时长    年代   评分 首映地点
31644  一个被隔绝的世界    46  纪录片/短片  瑞典  2001-10-25 00:00:00  8U  1948  7.8   美国

In [69]:
df.drop(31644,inplace=True)

In [38]:
df['时长']=df['时长'].astype('int')

ValueError: invalid literal for int() with base 10: '12J'

In [70]:
df[df.时长=='12J']

         名字  投票人数   类型  产地                 上映时间   时长    年代   评分 首映地点
32949  渔业危机    41  纪录片  英国  2009-06-19 00:00:00  12J  2008  8.2  USA

In [71]:
df.drop(32949,inplace=True)

In [72]:
df['时长']=df['时长'].astype('int')

In [73]:
df['时长'][:5]

0    142
1    116
2    116
3    142
4    171
Name: 时长, dtype: int32

#### 3.1.2 排序

###### 单值排序

默认排序

In [74]:
df[:10]  ##根据index进行排序

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
0,肖申克的救赎,692795,剧情/犯罪,美国,1994-09-10 00:00:00,142,1994,9.6,多伦多电影节
1,控方证人,42995,剧情/悬疑/犯罪,美国,1957-12-17 00:00:00,116,1957,9.5,美国
2,美丽人生,327855,剧情/喜剧/爱情,意大利,1997-12-20 00:00:00,116,1997,9.5,意大利
3,阿甘正传,580897,剧情/爱情,美国,1994-06-23 00:00:00,142,1994,9.4,洛杉矶首映
4,霸王别姬,478523,剧情/爱情/同性,中国大陆,1993-01-01 00:00:00,171,1993,9.4,香港
5,泰坦尼克号,157074,剧情/爱情/灾难,美国,2012-04-10 00:00:00,194,2012,9.4,中国大陆
6,辛德勒的名单,306904,剧情/历史/战争,美国,1993-11-30 00:00:00,195,1993,9.4,华盛顿首映
7,新世纪福音战士剧场版：Air/真心为你 新世紀エヴァンゲリオン劇場版 Ai,24355,剧情/动作/科幻/动画/奇幻,日本,1997-07-19 00:00:00,87,1997,9.4,日本
8,银魂完结篇：直到永远的万事屋 劇場版 銀魂 完結篇 万事屋よ,21513,剧情/动画,日本,2013-07-06 00:00:00,110,2013,9.4,日本
9,这个杀手不太冷,662552,剧情/动作/犯罪,法国,1994-09-14 00:00:00,133,1994,9.4,法国

按照投票人数进行排序

In [75]:
## 默认升序排列
df.sort_values(by='投票人数')[:5]

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
19797,女教徒,-118,剧情,法国,1966-05-06 00:00:00,135,1966,7.8,美国
19786,日本的垃圾去中国大陆 にっぽんの“ゴミ” 大陆へ渡る ～中国式リサイクル錬,-80,纪录片,日本,1905-06-26 00:00:00,60,2004,7.9,美国
19777,皇家大贼 皇家大,-80,剧情/犯罪,中国香港,1985-05-31 00:00:00,60,1985,6.3,美国
19804,女郎漫游仙境 ドレミファ娘の血は騒,5,喜剧/歌舞,日本,1985-11-03 00:00:00,80,1985,6.7,日本
19791,女教师 女教,8,剧情/犯罪,日本,1977-10-29 00:00:00,100,1977,6.6,日本

In [76]:
## 降序排列
df.sort_values(by='投票人数',ascending=False)[:5]

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
0,肖申克的救赎,692795,剧情/犯罪,美国,1994-09-10 00:00:00,142,1994,9.6,多伦多电影节
9,这个杀手不太冷,662552,剧情/动作/犯罪,法国,1994-09-14 00:00:00,133,1994,9.4,法国
22,盗梦空间,642134,剧情/动作/科幻/悬疑/冒险,美国,2010-09-01 00:00:00,148,2010,9.2,中国大陆
3,阿甘正传,580897,剧情/爱情,美国,1994-06-23 00:00:00,142,1994,9.4,洛杉矶首映
99,三傻大闹宝莱坞,549808,剧情/喜剧/爱情/歌舞,印度,2011-12-08 00:00:00,171,2009,9.1,中国大陆

按照年代进行排序

In [77]:
df.sort_values(by='年代')[:5]

            名字  投票人数           类型  产地                 上映时间  时长    年代   评分 首映地点
1700   朗德海花园场景   650           短片  英国           1888-10-14  60  1888  8.7   美国
14048     利兹大桥   126           短片  英国              1888-10  60  1888  7.2   美国
26170      恶作剧    51           短片  美国  1905-03-04 00:00:00  60  1890  4.8   美国
10627   可怜的比埃洛   176  喜剧/爱情/动画/短片  法国           1892-10-28  60  1892  7.5   法国
14455  迪克森实验音膜   121           短片  美国  1905-03-08 00:00:00  60  1894  7.2   美国

###### 多个值排序

先按照评分排序，再按照投票人数排序

In [78]:
df.sort_values(by=['评分','投票人数'],ascending=False)[:5]

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
9278,平安结祈 平安結,208,音乐,日本,2012-02-24 00:00:00,60,2012,9.9,美国
13882,武之舞,128,纪录片,中国大陆,1997-02-01 00:00:00,60,34943,9.9,美国
1110,NaN,76,科幻/纪录片,美国,1905-06-23 00:00:00,75,2001,9.9,美国
23559,未作回答的问题：伯恩斯坦哈佛六讲,61,纪录片,美国,1905-05-29 00:00:00,60,1973,9.9,美国
35470,NaN,46,纪录片/音乐,韩国,2013-10-31 00:00:00,90,2013,9.9,韩国

In [119]:
df.sort_values(by=['评分','投票人数'],ascending=[False,True])[:5]

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
25270,索科洛夫：巴黎现场,43,音乐,法国,2002-11-04 00:00:00,127,2002,9.9,美国
35465,未知电影,46,纪录片/音乐,韩国,2013-10-31 00:00:00,90,2013,9.9,韩国
23556,未作回答的问题：伯恩斯坦哈佛六讲,61,纪录片,美国,1905-05-29 00:00:00,60,1973,9.9,美国
1110,未知电影,76,科幻/纪录片,美国,1905-06-23 00:00:00,75,2001,9.9,美国
9278,平安结祈 平安結,208,音乐,日本,2012-02-24 00:00:00,60,2012,9.9,美国

#### 3.1.3基本统计分析

##### 描述性统计

dataframe.describe()：对dataframe中的数值数据进行描述性统计

In [81]:
df.describe()

                投票人数            时长            年代            评分
count   38736.000000  38736.000000  38736.000000  38736.000000
mean     6186.150764     89.051761   1998.788620      6.935649
std     26144.156471     83.334169    253.198744      1.270110
min      -118.000000      1.000000   1888.000000      2.000000
25%        98.000000     60.000000   1990.000000      6.300000
50%       341.000000     92.000000   2005.000000      7.100000
75%      1740.250000    106.000000   2010.000000      7.800000
max    692795.000000  11500.000000  39180.000000      9.900000

通过描述性统计，可以发现一些异常值，很多异常值往往是需要我们逐步去发现的

In [82]:
df[df.年代>2020]

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
13882,武之舞,128,纪录片,中国大陆,1997-02-01 00:00:00,60,34943,9.9,美国
17115,妈妈回来吧-中国打工村的孩子,49,纪录片,日本,2007-04-08 00:00:00,109,39180,8.9,美国

In [83]:
df[df.时长>1000]

            名字  投票人数        类型  产地                 上映时间     时长    年代   评分 首映地点
19690     怒海余生    54  剧情/家庭/冒险  美国  1937-09-01 00:00:00  11500  1937  7.9   美国
38730  喧闹村的孩子们    36        家庭  瑞典  1986-12-06 00:00:00   9200  1986  8.7   瑞典

In [84]:
df[df.投票人数<0]

,名字,投票人数,类型,产地,上映时间,时长,年代,评分,首映地点
19777,皇家大贼 皇家大,-80,剧情/犯罪,中国香港,1985-05-31 00:00:00,60,1985,6.3,美国
19786,日本的垃圾去中国大陆 にっぽんの“ゴミ” 大陆へ渡る ～中国式リサイクル錬,-80,纪录片,日本,1905-06-26 00:00:00,60,2004,7.9,美国
19797,女教徒,-118,剧情,法国,1966-05-06 00:00:00,135,1966,7.8,美国

In [85]:
df.drop(df[df.年代>2020].index,inplace=True)
df.drop(df[df.时长>1000].index,inplace=True)
df.drop(df[df.投票人数<0].index,inplace=True)
df.describe()

                投票人数            时长            年代            评分
count   38729.000000  38729.000000  38729.000000  38729.000000
mean     6187.269152     88.522425   1996.980945      6.935420
std     26146.386725     37.945673     19.934655      1.270034
min         5.000000      1.000000   1888.000000      2.000000
25%        98.000000     60.000000   1990.000000      6.300000
50%       341.000000     92.000000   2005.000000      7.100000
75%      1741.000000    106.000000   2010.000000      7.800000
max    692795.000000    958.000000   2016.000000      9.900000

In [86]:
##删除 行 后，重新分配 索引index
df.index=range(len(df))

##### 最值

In [87]:
df['投票人数'].max()

692795

In [88]:
df['投票人数'].min()

5

##### 均值和中值

In [89]:
df['投票人数'].mean()

6187.269152314803

In [90]:
df['投票人数'].median()

341.0

##### 方差和标准差

In [91]:
df['评分'].var()

1.6129862161070732

In [92]:
df['评分'].std()

1.2700339428956509

##### 求和

In [93]:
df['投票人数'].sum()

239626747

##### 相关系数、协方差

In [94]:
## 相关性
df[['投票人数','评分']].corr()

          投票人数        评分
投票人数  1.000000  0.122957
评分    0.122957  1.000000

In [95]:
## 协方差
df[['投票人数','评分']].cov()

              投票人数           评分
投票人数  6.836335e+08  4083.001838
评分    4.083002e+03     1.612986

##### 计数
##### 数据替换

In [96]:
len(df)

38729

In [97]:
## 某列的所有取值
df['产地'].unique()

array(['美国', '意大利', '中国大陆', '日本', '法国', '英国', '韩国', '中国香港', '阿根廷', '德国',
       '印度', '其他', '加拿大', '波兰', '泰国', '澳大利亚', '西班牙', '俄罗斯', '中国台湾', '荷兰',
       '丹麦', '比利时', 'USA', '苏联', '墨西哥', '巴西', '瑞典', '西德'], dtype=object)

In [98]:
len(df['产地'].unique())

28

产地中包含了一些重复数据，比如美国和USA，德国和西德，俄罗斯和苏联

我们可以通过数据替换的方法将这些相同的国家的电影数据合并一下

In [99]:
df['产地'].replace('USA','美国',inplace=True)
df['产地'].replace(['西德','苏联'],['德国','俄罗斯'],inplace=True)
len(df['产地'].unique())

25

计算每一年代电影的数量

In [100]:
df['年代'].value_counts()[:10]

2012    2042
2013    2001
2008    1963
2014    1887
2010    1886
2011    1866
2009    1862
2007    1711
2015    1592
2006    1515
Name: 年代, dtype: int64

电影产出前5位的国家或地区

In [101]:
df['产地'].value_counts()[:5]

美国      11978
日本       5051
中国大陆     3802
中国香港     2851
法国       2816
Name: 产地, dtype: int64

In [57]:
df.to_excel('./movie_data2.xlsx')

#### 3.1.4 数据透视

Pandas提供了一个数据透视表功能，名为pivot_table。<br>
使用pivot_table的一个挑战是，你需要确保你理解你的数据，并清楚的知道你通过透视表解决了什么问题，虽然pivot_table看起来知识一个简单的函数，但是它能够快速的对数据进行强大的分析。

##### 基础形式

In [58]:
pd.set_option('max_columns',100)  ##设置显示的最大列
pd.set_option('max_rows',500)  ##设置显示的最大行

In [59]:
pd.pivot_table(df,index=['年代'])

              投票人数          时长        评分
年代
1888    388.000000   60.000000  7.950000
1890     51.000000   60.000000  4.800000
1892    176.000000   60.000000  7.500000
1894    112.666667   60.000000  6.633333
1895    959.875000   60.000000  7.575000
1896    984.250000   60.000000  7.037500
1897     67.000000   60.000000  6.633333
1898    578.500000   60.000000  7.450000
1899     71.000000    9.500000  6.900000
1900    175.285714   36.714286  7.228571
1901    164.500000   47.250000  7.250000
1902   1934.166667   34.666667  7.483333
1903    295.625000   29.625000  6.968750
1904    195.875000   41.250000  7.212500
1905    332.600000   43.800000  6.820000
1906    189.857143   30.571429  7.342857
1907    213.600000   31.800000  7.020000
1908    258.833333   34.166667  7.150000
1909     58.600000   20.600000  7.560000
1910    105.200000   41.800000  6.940000
1911    240.000000   25.750000  7.375000
1912    152.200000   16.400000  7.920000
1913     66.125000   57.750000  6.862500
1914    104.923077   25.923077  6.473077
1915    314.900000   56.800000  7.260000
1916    613.666667   43.833333  7.758333
1917    124.416667   31.333333  7.075000
1918    357.083333   35.166667  7.200000
1919    179.850000   62.400000  7.490000
1920    636.500000   59.357143  7.492857
1921    729.818182   57.363636  7.750000
1922    767.090909   66.363636  7.804545
1923    426.000000   74.055556  7.883333
1924    371.785714   81.178571  8.053571
1925   1104.280000   84.440000  7.788000
1926    443.608696   80.304348  7.773913
1927    695.275862   87.241379  7.751724
1928    404.825000   71.775000  7.945000
1929    740.542857   69.371429  7.440000
1930    555.080000   74.160000  7.360000
1931   1468.666667   78.523810  7.483333
1932    600.081081   77.540541  7.294595
1933    729.720000   76.360000  7.430000
1934    776.490196   83.196078  7.519608
1935    887.695652   73.673913  7.515217
1936   1465.466667   76.266667  7.635000
1937   1580.224490   85.510204  7.575510
1938    552.000000   85.973684  7.736842
1939   5911.857143   97.387755  7.520408
1940   5548.743590   92.820513  7.571795
1941   1552.808511   89.127660  7.427660
1942   2607.754717   78.264151  7.554717
1943    742.842105   78.456140  7.615789
1944   1007.370370   81.925926  7.538889
1945    989.020408   86.959184  7.673469
1946   1034.457627   85.016949  7.606780
1947    439.400000   87.120000  7.453333
1948   1186.505747   88.206897  7.657471
1949    641.685393   81.988764  7.646067
1950   2235.026316   80.157895  7.655263
1951    956.101266   85.632911  7.636709
1952   1473.540230   81.528736  7.743678
1953   4786.113636   84.170455  7.567045
1954   2180.245098   85.549020  7.702941
1955   1983.739130   83.669565  7.580000
1956   1054.605442   76.408163  7.600000
1957   2973.579439   87.355140  7.652336
1958    886.196721   82.975410  7.536885
1959   1725.070312   90.070312  7.571875
1960   1446.274809  101.312977  7.569466
1961   3186.833333   98.215686  7.744118
1962   1972.118881   91.615385  7.704895
1963   1184.027972   92.020979  7.536364
1964   1107.763736   89.714286  7.523077
1965   1988.184049   90.478528  7.576074
1966   1319.525140   89.486034  7.518994
1967   1237.289773   91.590909  7.484659
1968   1096.220930   91.744186  7.317442
1969    593.111111   98.666667  7.370048
1970    676.789474   96.973684  7.291053
1971   1368.506849   96.315068  7.155708
1972   2299.096618   96.289855  7.268116
1973    800.103286   94.882629  7.250235
1974   1685.789238   95.318386  7.062332
1975   2222.739796   97.566327  7.071429
1976   1340.618026   95.055794  7.107725
1977    957.127273   98.031818  7.148182
1978   1001.820896   94.467662  7.096517
1979   1878.621145   96.000000  7.296035
1980   2407.683036   94.178571  7.186607
1981   1609.062044   93.321168  7.157299
1982   2142.729323   91.984962  7.297368
1983   1541.191336   92.169675  7.310108
1984   2667.173469   90.918367  7.375170
1985   1588.096573   93.616822  7.278505
1986   2828.506173   89.145062  7.256790
1987   3128.775510   88.938776  7.284548
1988   4800.227621   88.859335  7.265729
1989   2994.417303   88.458015  7.210687
1990   4965.587786   91.882952  7.149109
1991   4685.819512   93.370732  7.154634
1992   5486.133333   92.572414  7.223678
1993   8117.759637   95.269841  7.195692
1994  11479.255061   91.344130  7.262348
1995   8132.605317   94.441718  7.289366
1996   5095.883946   95.243714  7.258801
1997   8243.938547   94.970205  7.330168
1998   7431.790295   91.131716  7.238302
1999   7137.049600   92.457600  7.188000
2000   5907.770178   92.191518  7.134063
2001   8489.757246   90.958937  7.110145
2002   6552.593333   91.584444  7.069778
2003   7891.964248   90.558360  7.137750
2004   8587.632599   90.424670  7.031366
2005   6506.110847   92.080760  7.030008
2006   7278.260726   90.144554  6.914719
2007   6253.837522   86.628288  6.875102
2008   6750.996943   85.144167  6.910647
2009   8716.364662   86.384533  6.750000
2010   9576.387593   83.434252  6.770361
2011   8763.110397   84.125938  6.577010
2012   7082.787463   85.099902  6.458374
2013   7603.723138   84.902049  6.392604
2014   7723.302597   85.997880  6.259777
2015   7841.408291   89.863693  6.141960
2016   7176.019380   91.329457  5.868217

##### 多个索引  index=['','']

实际上，大多数的pivot_table参数可以通过列表获取多个值

In [61]:
pd.set_option('max_columns',100)
pd.set_option('max_rows',1600)
pd.pivot_table(df,index=['年代','产地'])

                   投票人数          时长        评分
年代   产地
1888 英国      388.000000   60.000000  7.950000
1890 美国       51.000000   60.000000  4.800000
1892 法国      176.000000   60.000000  7.500000
1894 法国      148.000000   60.000000  7.000000
     美国       95.000000   60.000000  6.450000
1895 法国      959.875000   60.000000  7.575000
1896 法国     1874.250000   60.000000  7.650000
     美国       55.666667   60.000000  6.366667
     英国      210.000000   60.000000  6.600000
1897 法国       67.000000   60.000000  6.633333
1898 法国      991.000000   60.000000  8.500000
     英国      166.000000   60.000000  6.400000
1899 法国       71.000000    9.500000  6.900000
1900 法国       52.000000    5.666667  7.100000
     美国      212.500000   60.000000  7.450000
     英国      323.000000   60.000000  7.200000
1901 法国      142.000000    9.000000  7.700000
     英国      172.000000   60.000000  7.100000
1902 法国     3818.000000   26.000000  8.066667
     美国       50.333333   43.333333  6.900000
1903 法国       81.600000   21.500000  6.960000
     美国      824.500000   47.750000  6.850000
     英国      308.000000   34.000000  7.250000
1904 法国      217.714286   38.571429  7.500000
     美国       43.000000   60.000000  5.200000
1905 中国大陆    137.000000   30.000000  8.400000
     美国       45.666667   43.000000  5.766667
     英国     1389.000000   60.000000  8.400000
1906 意大利      37.000000    6.000000  7.000000
     法国       77.333333    9.333333  7.033333
     美国      425.500000   60.000000  7.750000
     英国      209.000000   60.000000  7.800000
1907 法国      213.600000   31.800000  7.020000
1908 法国      458.666667   60.000000  6.966667
     美国       33.500000    8.500000  6.950000
     西班牙     110.000000    8.000000  8.100000
1909 美国       58.600000   20.600000  7.560000
1910 法国       78.666667   60.000000  6.533333
     美国      145.000000   14.500000  7.550000
1911 意大利     297.000000   71.000000  8.200000
     美国      299.000000   12.000000  7.450000
     荷兰       65.000000    8.000000  6.400000
1912 俄罗斯     511.000000   12.000000  8.100000
     法国       71.500000   21.500000  7.750000
     美国       53.500000   13.500000  8.000000
1913 俄罗斯      54.000000   60.000000  7.400000
     德国      108.000000   85.000000  7.400000
     意大利      42.000000  120.000000  7.300000
     法国       40.000000    7.000000  6.700000
     瑞典       48.000000   60.000000  7.800000
     美国       79.000000   43.333333  6.100000
1914 意大利     204.000000  148.000000  8.300000
     法国       31.000000   59.000000  7.600000
     美国      103.875000   19.458333  6.350000
1915 俄罗斯      41.000000   46.000000  7.800000
     意大利     134.000000   40.000000  7.600000
     法国       89.500000  202.500000  7.200000
     美国      371.500000   40.312500  7.212500
1916 德国       48.000000   35.000000  6.100000
     美国      665.090909   44.636364  7.909091
1917 俄罗斯      86.000000   60.000000  8.400000
     德国       46.000000   48.000000  6.700000
     瑞典       46.000000   48.000000  7.700000
     美国      146.111111   24.444444  6.900000
1918 德国      190.000000   45.000000  7.300000
     瑞典       30.000000  136.000000  7.000000
     美国      406.500000   24.100000  7.210000
1919 丹麦       57.000000   75.000000  7.700000
     德国      118.000000   71.571429  7.314286
     法国       76.000000  166.000000  8.600000
     美国      239.818182   46.000000  7.481818
1920 其他       56.000000   43.000000  5.600000
     德国     1514.750000   92.750000  7.375000
     美国      310.666667   46.333333  7.755556
1921 丹麦       91.000000  112.000000  8.200000
     德国      129.600000   64.800000  7.200000
     法国       55.000000   95.000000  8.100000
     瑞典      804.000000   93.000000  8.000000
     美国     1107.923077   41.769231  7.853846
1922 中国大陆   1600.000000   22.000000  8.100000
     丹麦      343.500000   81.000000  7.850000
     德国      963.000000  137.200000  8.080000
     美国      698.142857   42.142857  7.678571
1923 中国大陆     41.000000  100.000000  8.100000
     俄罗斯      54.000000    5.000000  6.900000
     德国       68.000000   90.000000  7.400000
     法国      157.500000   97.500000  7.875000
     美国      681.800000   68.800000  7.890000
     英国       57.000000   60.000000  9.100000
1924 俄罗斯      94.666667   68.333333  7.866667
     德国      463.750000   85.125000  8.062500
     法国      161.600000   60.800000  7.740000
     美国      539.500000   88.600000  8.100000
     英国      106.500000   98.500000  8.850000
1925 丹麦       87.000000  107.000000  6.900000
     俄罗斯     283.000000   55.000000  7.700000
     其他     8835.000000   75.000000  8.500000
     德国      212.333333   90.333333  8.000000
     日本       77.000000   74.000000  7.600000
     法国      137.250000   75.000000  8.025000
     美国     1391.000000   91.583333  7.783333
     英国      164.000000   75.000000  6.800000
1926 中国大陆     84.000000   60.000000  6.900000
     俄罗斯     193.000000   78.000000  7.800000
     德国      612.400000   87.600000  8.120000
     日本      314.000000   59.000000  8.000000
     法国      114.500000   62.750000  7.725000
     美国      634.000000   89.444444  7.666667
1927 中国大陆    366.000000   74.500000  7.750000
     俄罗斯      49.000000   90.666667  7.700000
     德国     5251.000000  109.000000  8.600000
     法国      127.000000   76.000000  7.700000
     美国      472.357143   87.357143  7.828571
     英国      511.333333   96.000000  6.966667
1928 中国大陆     69.000000   60.000000  7.400000
     俄罗斯     239.500000   92.500000  8.350000
     其他       40.000000   60.000000  7.800000
     德国      172.250000   63.000000  7.800000
     法国      609.857143   73.285714  7.814286
     美国      471.200000   70.600000  8.195000
     英国      229.250000   94.500000  7.150000
     荷兰      306.000000   11.000000  7.500000
1929 中国大陆     64.500000   68.000000  5.850000
     俄罗斯    1851.333333   86.333333  8.133333
     其他       72.000000   85.000000  7.100000
     德国      390.000000  108.600000  7.840000
     日本      126.400000   44.600000  7.080000
     比利时      37.000000   33.000000  7.400000
     法国     4356.333333   20.000000  7.700000
     瑞典       32.000000   87.000000  8.100000
     美国      230.625000   71.125000  7.450000
     英国      239.800000   84.200000  7.200000
     荷兰     1400.000000   12.000000  8.400000
1930 俄罗斯     217.000000   75.000000  7.900000
     德国      651.500000   99.000000  7.700000
     日本       73.200000   47.400000  6.800000
     法国      725.833333   53.500000  7.883333
     美国      735.100000   91.900000  7.220000
     英国      285.000000  104.000000  7.200000
1931 中国大陆    870.000000  119.000000  7.850000
     俄罗斯      41.000000   67.000000  8.100000
     其他       63.000000   20.000000  7.100000
     墨西哥     115.000000   11.000000  7.300000
     巴西       69.000000  114.000000  7.900000
     德国     2910.600000  102.200000  7.580000
     日本      399.833333   53.500000  7.350000
     法国      288.200000   83.200000  7.360000
     美国     2395.823529   80.647059  7.588235
     英国      239.500000   84.500000  6.200000
     荷兰       55.000000   60.000000  8.000000
1932 中国大陆    153.000000   77.000000  7.400000
     俄罗斯      33.000000   60.000000  7.000000
     德国      318.666667   79.666667  7.500000
     日本      797.000000   95.333333  7.800000
     法国      149.666667   90.000000  7.500000
     美国      726.640000   74.960000  7.220000
     英国       55.000000   63.000000  6.600000
1933 中国大陆    250.000000   99.000000  7.575000
     其他      227.000000   82.000000  7.200000
     德国      231.750000   91.500000  8.000000
     日本      142.125000   77.250000  7.787500
     比利时      89.000000   36.000000  8.000000
     法国      679.000000   67.333333  7.466667
     美国     1116.259259   73.740741  7.181481
     英国      158.000000   97.000000  7.500000
     西班牙     772.000000   30.000000  7.900000
1934 中国大陆   1434.857143   95.000000  7.742857
     俄罗斯     122.000000   82.333333  7.300000
     意大利      90.500000   88.500000  7.300000
     日本      218.000000   68.666667  7.416667
     法国      287.428571  104.571429  7.800000
     美国     1110.681818   79.090909  7.481818
     英国      313.750000   67.500000  7.275000
1935 中国大陆    412.500000   87.500000  7.575000
     中国香港    101.000000   60.000000  6.500000
     德国     3393.333333   51.000000  7.933333
     日本      199.333333   79.666667  7.733333
     法国      176.500000   50.500000  7.000000
     美国      652.250000   73.785714  7.478571
     英国     4545.500000   90.500000  7.650000
1936 中国大陆    223.500000   70.500000  7.950000
     墨西哥      42.000000   60.000000  7.000000
     日本      420.428571   69.714286  7.814286
     法国      273.125000   85.500000  7.512500
     瑞典       76.000000   93.000000  7.400000
     美国     2302.676471   76.382353  7.641176
     英国      699.400000   74.400000  7.460000
1937 中国大陆   3356.500000  107.500000  7.625000
     俄罗斯     304.500000   69.500000  7.750000
     日本      278.250000   90.500000  7.375000
     法国     1123.750000  104.500000  7.400000
     美国     1913.862069   83.448276  7.768966
     英国      381.000000   70.166667  6.800000
1938 中国大陆     49.000000   87.000000  6.900000
     中国香港     39.000000   60.000000  7.000000
     俄罗斯     179.000000  105.000000  7.250000
     德国     1209.000000  108.500000  9.000000
     日本      102.000000   57.500000  7.900000
     法国      301.400000  106.000000  7.240000
     美国      537.285714   79.476190  7.819048
     英国     1279.500000   94.750000  7.850000
1939 中国大陆    129.500000   99.500000  6.900000
     中国香港     47.000000   60.000000  6.500000
     俄罗斯     458.000000  115.000000  7.100000
     日本      403.250000   84.000000  7.525000
     法国     1946.000000  101.500000  8.100000
     美国     8290.088235   97.147059  7.635294
     英国      272.750000  110.250000  7.025000
1940 中国大陆    703.000000   96.000000  7.600000
     俄罗斯      72.000000  120.000000  7.500000
     德国       36.000000   98.000000  6.200000
     日本       50.000000  124.000000  6.200000
     瑞典       38.000000   88.000000  6.500000
     美国     7135.466667   91.400000  7.770000
     英国      359.500000   88.000000  7.050000
1941 中国大陆   1013.000000   81.000000  7.050000
     日本      340.000000   86.500000  7.875000
     法国       35.000000   81.000000  6.900000
     美国     1829.081081   86.972973  7.432432
     英国      628.333333  127.333333  7.200000
1942 丹麦       33.000000   12.000000  5.900000
     俄罗斯      98.000000   60.000000  6.700000
     日本      516.666667   90.000000  7.533333
     法国      151.000000  102.000000  7.150000
     美国     3162.813953   78.488372  7.667442
     英国       75.666667   75.666667  7.066667
1943 中国大陆     83.000000  106.000000  6.800000
     丹麦      765.000000   97.000000  8.500000
     德国       74.500000  102.000000  7.300000
     意大利     373.000000  140.000000  7.600000
     日本      613.500000   62.000000  7.825000
     法国      515.666667   83.833333  7.533333
     美国      857.414634   73.439024  7.609756
     英国      270.000000  163.000000  8.100000
1944 俄罗斯     808.000000  103.000000  8.100000
     墨西哥      38.000000   76.000000  7.000000
     德国      108.000000   97.000000  8.300000
     意大利     631.000000   84.000000  8.300000
     日本       61.750000   80.000000  6.925000
     法国       37.000000  105.000000  7.200000
     瑞典      304.000000  101.000000  7.600000
     美国     1319.410256   79.897436  7.656410
     英国      153.600000   84.400000  6.860000
1945 意大利    3062.000000  103.000000  7.800000
     日本      651.750000   70.250000  6.775000
     法国      953.666667  117.333333  7.933333
     美国      956.222222   83.638889  7.763889
     英国     1101.600000  102.800000  7.560000
1946 丹麦       43.000000   13.000000  6.300000
     其他       64.000000   60.000000  7.700000
     德国      171.000000   85.000000  7.600000
     意大利     731.666667   98.000000  8.100000
     日本      266.333333   92.000000  6.900000
     法国      573.750000   77.250000  7.275000
     瑞典      136.500000   94.000000  6.750000
     美国     1311.175000   84.300000  7.730000
     英国      686.500000  104.750000  7.600000
1947 中国大陆   1333.285714  112.285714  7.657143
     中国香港     55.000000   91.666667  6.500000
     丹麦       47.000000   14.000000  6.900000
     俄罗斯     291.000000  100.000000  7.900000
     墨西哥      32.000000   92.000000  5.700000
     意大利     111.000000   10.000000  7.600000
     日本      480.000000   89.666667  8.000000
     法国      161.833333   70.500000  7.500000
     瑞典       92.500000   79.000000  5.350000
     美国      402.574468   87.212766  7.561702
     英国      486.333333  102.666667  7.566667
1948 中国大陆   2654.142857   90.857143  7.771429
     中国香港    209.333333   98.666667  6.600000
     丹麦       50.000000   11.000000  6.800000
     俄罗斯      42.000000  189.000000  8.200000
     其他       48.000000  102.500000  7.750000
     意大利    7065.000000   82.000000  8.080000
     日本      847.666667   95.666667  7.600000
     法国      178.250000   69.500000  7.700000
     波兰       45.000000  115.000000  7.700000
     瑞典      229.500000   93.500000  7.350000
     美国      590.769231   83.500000  7.638462
     英国     2337.666667  119.666667  7.983333
1949 中国大陆   1620.142857   84.142857  7.500000
     中国香港     36.333333  145.666667  7.600000
     丹麦       32.000000   10.000000  6.800000
     俄罗斯     134.500000   79.000000  6.750000
     其他       89.666667   64.000000  6.966667
     墨西哥      73.000000   92.000000  7.200000
     意大利     167.000000  108.000000  7.600000
     日本     1754.714286   98.285714  7.628571
     法国      501.142857   79.285714  7.857143
     瑞典      817.500000   90.500000  7.150000
     美国      334.354167   74.604167  7.802083
     英国     1625.000000  100.857143  7.428571
1950 中国大陆    779.333333  108.666667  7.300000
     中国香港     68.500000   89.000000  6.925000
     丹麦       33.000000    7.000000  6.100000
     其他       64.333333   97.333333  7.366667
     墨西哥     652.000000   85.000000  8.300000
     意大利     603.750000   93.250000  7.625000
     日本    24436.500000   99.000000  7.800000
     法国      456.571429   63.571429  7.728571
     瑞典      115.500000   91.000000  6.700000
     美国     1433.375000   72.575000  7.882500
     英国      777.750000  100.250000  7.325000
1951 中国大陆    436.250000  134.000000  7.025000
     其他       99.000000   20.000000  7.600000
     印度     2287.000000  193.000000  8.300000
     墨西哥      73.000000   86.000000  7.300000
     意大利     937.666667  108.000000  8.200000
     日本      818.888889  105.333333  7.544444
     法国      738.600000  107.000000  7.900000
     波兰       38.000000   10.000000  6.400000
     瑞典      400.666667   96.333333  7.533333
     美国     1221.292683   69.048780  7.719512
     英国      613.900000   99.300000  7.450000
1952 中国大陆   1544.333333   81.333333  7.533333
     中国香港     47.000000   60.000000  7.800000
     俄罗斯     106.000000   60.000000  8.000000
     加拿大     116.000000   60.000000  7.300000
     墨西哥      71.000000   72.500000  6.350000
     意大利     836.000000   96.166667  7.883333
     日本     1603.375000  110.125000  7.875000
     法国      629.125000   83.875000  7.837500
     波兰       69.000000  121.000000  7.400000
     瑞典      255.000000  107.000000  7.600000
     美国     1928.058824   74.686275  7.776471
     英国      405.750000   89.500000  7.675000
1953 中国大陆    802.000000  120.000000  7.100000
     中国香港    120.000000  117.500000  7.150000
     其他       45.333333   72.000000  7.133333
     印度       43.000000  131.000000  7.800000
     墨西哥     160.000000   86.500000  7.250000
     意大利     348.600000   98.400000  7.390000
     日本     4419.000000   96.600000  7.930000
     法国     1694.166667   88.166667  8.116667
     瑞典     1035.000000   83.000000  7.466667
     美国     7318.857143   75.693878  7.520408
     西班牙      67.000000   95.000000  8.000000
1954 中国大陆   2255.250000   84.500000  7.675000
     中国香港     42.000000   60.000000  7.700000
     俄罗斯      67.666667   95.000000  6.700000
     其他      254.500000  105.000000  7.700000
     墨西哥     207.666667   90.333333  6.866667
     德国      114.500000   83.500000  7.350000
     意大利    2113.428571  115.000000  7.857143
     日本     6756.400000  107.100000  8.080000
     法国      609.600000   99.000000  7.400000
     瑞典      401.000000   96.000000  7.800000
     美国     2035.098039   77.509804  7.725490
     英国     2007.000000   77.727273  7.863636
1955 中国大陆   9661.125000   63.375000  7.687500
     中国香港    204.000000   83.250000  6.950000
     丹麦      781.000000  126.000000  8.400000
     俄罗斯     166.000000   92.500000  7.300000
     其他    13582.400000   65.800000  8.200000
     加拿大     351.000000   60.000000  5.800000
     印度     1628.000000  122.000000  8.800000
     墨西哥      83.000000   90.000000  7.250000
     德国       40.000000  115.000000  7.500000
     意大利     993.500000  102.000000  7.950000
     日本      757.111111  105.222222  7.677778
     法国     1906.125000   87.500000  7.937500
     波兰      604.000000   83.000000  7.800000
     瑞典      746.000000   97.500000  7.800000
     美国      820.016949   76.745763  7.483051
     英国      454.375000  115.000000  7.525000
     西班牙     653.000000   88.000000  8.200000
1956 中国大陆   1418.076923   65.076923  7.776923
     中国香港    118.800000   82.800000  7.480000
     俄罗斯     326.400000   65.800000  7.980000
     其他     4781.800000   68.600000  7.500000
     印度      946.000000  110.000000  8.700000
     意大利    5910.000000  133.000000  8.200000
     日本      493.625000   98.437500  7.700000
     法国     2797.076923   72.692308  7.838462
     美国      499.097561   71.048780  7.458537
     英国      228.333333  104.000000  7.700000
1957 中国大陆    178.166667   81.333333  7.450000
     中国香港     72.750000   97.000000  7.350000
     俄罗斯     421.000000   90.666667  8.333333
     其他     5875.750000   98.250000  8.025000
     加拿大     302.000000   12.000000  7.800000
     印度       64.500000  159.000000  7.450000
     意大利    2409.800000  106.600000  7.900000
     日本      964.363636  106.090909  7.500000
     法国      211.600000   49.600000  8.120000
     波兰      338.000000   32.600000  7.180000
     瑞典    19832.000000   93.500000  8.450000
     美国     4146.372549   87.764706  7.670588
     英国     1885.250000   87.750000  7.287500
1958 中国大陆   2112.000000   59.307692  7.630769
     中国香港    109.666667   85.666667  7.166667
     俄罗斯     295.000000   97.333333  8.266667
     其他       78.000000   76.571429  7.342857
     印度      392.000000  100.000000  8.300000
     德国      165.000000  101.500000  7.850000
     意大利    1289.666667  115.333333  8.100000
     日本      867.615385   95.615385  7.400000
     法国      711.714286   72.357143  7.550000
     波兰      502.000000   63.000000  7.583333
     瑞典      385.000000   92.000000  7.850000
     美国     1021.777778   89.377778  7.548889
     英国      371.000000   94.625000  6.912500
     荷兰      160.000000   11.000000  8.700000
     阿根廷     176.000000   10.000000  7.500000
1959 中国大陆   2811.733333   80.933333  7.540000
     中国香港    230.000000   90.000000  7.855556
     俄罗斯     561.428571   80.428571  7.842857
     其他      120.000000   72.250000  7.875000
     印度      723.000000  105.000000  8.700000
     墨西哥     243.000000   94.000000  7.900000
     巴西      270.000000   80.000000  6.800000
     德国      228.333333  102.000000  7.233333
     意大利     139.666667  106.166667  7.683333
     日本      859.416667  107.666667  7.800000
     法国     3742.176471   75.176471  7.547059
     波兰      349.000000   47.000000  7.550000
     美国     2348.307692   97.923077  7.441026
     英国      276.750000   96.750000  7.337500
1960 中国大陆   1488.714286   67.714286  7.628571
     中国香港    233.909091   92.000000  7.336364
     俄罗斯     254.333333  129.666667  7.966667
     其他      251.000000   79.000000  7.516667
     印度       79.500000  149.500000  7.850000
     墨西哥     116.000000   95.000000  7.400000
     德国      134.000000   97.000000  7.500000
     意大利    1438.888889  109.888889  7.777778
     日本      623.884615   99.615385  7.619231
     法国     2202.333333   93.944444  7.944444
     波兰      106.200000   88.600000  7.040000
     瑞典     3922.000000   88.000000  8.000000
     美国     3310.740741  120.185185  7.451852
     英国      474.250000   98.916667  7.300000
     韩国     1521.000000  111.000000  6.800000

##### 指定需要统计汇总的数据  values

In [99]:
pd.pivot_table(df,index=['年代','产地'],values=['评分'])

               评分
年代   产地
1888 英国  7.950000
1890 美国  4.800000
1892 法国  7.500000
1894 法国  7.000000
     美国  6.450000
...           ...
2016 法国  7.475000
     美国  6.540909
     英国  7.200000
     韩国  5.730000
2017 美国  6.935704

[1511 rows x 1 columns]

##### 指定函数  aggfunc

In [62]:
pd.pivot_table(df,index=['年代','产地'],values=['投票人数'],aggfunc=np.sum)

              投票人数
年代   产地
1888 英国        776
1890 美国         51
1892 法国        176
1894 法国        148
     美国        190
1895 法国       7679
1896 法国       7497
     美国        167
     英国        210
1897 法国        201
1898 法国        991
     英国        166
1899 法国        142
1900 法国        156
     美国        425
     英国        646
1901 法国        142
     英国        516
1902 法国      11454
     美国        151
1903 法国        816
     美国       3298
     英国        616
1904 法国       1524
     美国         43
1905 中国大陆      137
     美国        137
     英国       1389
1906 意大利        37
     法国        232
     美国        851
     英国        209
1907 法国       1068
1908 法国       1376
     美国         67
     西班牙       110
1909 美国        293
1910 法国        236
     美国        290
1911 意大利       297
     美国        598
     荷兰         65
1912 俄罗斯       511
     法国        143
     美国        107
1913 俄罗斯        54
     德国        108
     意大利        42
     法国         40
     瑞典         48
     美国        237
1914 意大利       204
     法国         31
     美国       2493
1915 俄罗斯        41
     意大利       134
     法国        179
     美国       5944
1916 德国         48
     美国       7316
1917 俄罗斯        86
     德国         46
     瑞典         46
     美国       1315
1918 德国        190
     瑞典         30
     美国       4065
1919 丹麦         57
     德国        826
     法国         76
     美国       2638
1920 其他         56
     德国       6059
     美国       2796
1921 丹麦         91
     德国        648
     法国        110
     瑞典        804
     美国      14403
1922 中国大陆     1600
     丹麦        687
     德国       4815
     美国       9774
1923 中国大陆       41
     俄罗斯        54
     德国         68
     法国        630
     美国       6818
     英国         57
1924 俄罗斯       284
     德国       3710
     法国        808
     美国       5395
     英国        213
1925 丹麦         87
     俄罗斯       566
     其他       8835
     德国        637
     日本         77
     法国        549
     美国      16692
     英国        164
1926 中国大陆       84
     俄罗斯       579
     德国       3062
     日本        314
     法国        458
     美国       5706
1927 中国大陆      732
     俄罗斯       147
     德国      10502
     法国        635
     美国       6613
     英国       1534
1928 中国大陆       69
     俄罗斯       479
     其他         40
     德国        689
     法国       4269
     美国       9424
     英国        917
     荷兰        306
1929 中国大陆      129
     俄罗斯      5554
     其他         72
     德国       1950
     日本        632
     比利时        37
     法国      13069
     瑞典         32
     美国       1845
     英国       1199
     荷兰       1400
1930 俄罗斯       217
     德国       1303
     日本        366
     法国       4355
     美国       7351
     英国        285
1931 中国大陆     1740
     俄罗斯        41
     其他         63
     墨西哥       115
     巴西         69
     德国      14553
     日本       2399
     法国       1441
     美国      40729
     英国        479
     荷兰         55
1932 中国大陆      153
     俄罗斯        33
     德国        956
     日本       2391
     法国        449
     美国      18166
     英国         55
1933 中国大陆     1000
     其他        227
     德国        927
     日本       1137
     比利时        89
     法国       2037
     美国      30139
     英国        158
     西班牙       772
1934 中国大陆    10044
     俄罗斯       366
     意大利       181
     日本       1308
     法国       2012
     美国      24435
     英国       1255
1935 中国大陆     1650
     中国香港      101
     德国      10180
     日本       1196
     法国        353
     美国      18263
     英国       9091
1936 中国大陆      894
     墨西哥        42
     日本       2943
     法国       2185
     瑞典         76
     美国      78291
     英国       3497
1937 中国大陆    13426
     俄罗斯       609
     日本       1113
     法国       4495
     美国      55502
     英国       2286
1938 中国大陆       49
     中国香港       39
     俄罗斯       358
     德国       2418
     日本        204
     法国       1507
     美国      11283
     英国       5118
1939 中国大陆      259
     中国香港       47
     俄罗斯       916
     日本       1613
     法国       3892
     美国     281863
     英国       1091
1940 中国大陆      703
     俄罗斯        72
     德国         36
     日本         50
     瑞典         38
     美国     214064
     英国       1438
1941 中国大陆     2026
     日本       1360
     法国         35
     美国      67676
     英国       1885
1942 丹麦         33
     俄罗斯        98
     日本       1550
     法国        302
     美国     136001
     英国        227
1943 中国大陆       83
     丹麦        765
     德国        149
     意大利       373
     日本       2454
     法国       3094
     美国      35154
     英国        270
1944 俄罗斯       808
     墨西哥        38
     德国        108
     意大利       631
     日本        247
     法国         37
     瑞典        304
     美国      51457
     英国        768
1945 意大利      3062
     日本       2607
     法国       2861
     美国      34424
     英国       5508
1946 丹麦         43
     其他         64
     德国        171
     意大利      2195
     日本        799
     法国       2295
     瑞典        273
     美国      52447
     英国       2746
1947 中国大陆     9333
     中国香港      165
     丹麦         47
     俄罗斯       291
     墨西哥        32
     意大利       111
     日本       1440
     法国        971
     瑞典        185
     美国      18921
     英国       1459
1948 中国大陆    18579
     中国香港      628
     丹麦         50
     俄罗斯        42
     其他         96
     意大利     35325
     日本       2543
     法国        713
     波兰         45
     瑞典        459
     美国      30720
     英国      14026
1949 中国大陆    11341
     中国香港      109
     丹麦         32
     俄罗斯       269
     其他        269
     墨西哥        73
     意大利       167
     日本      12283
     法国       3508
     瑞典       1635
     美国      16049
     英国      11375
1950 中国大陆     4676
     中国香港      274
     丹麦         33
     其他        193
     墨西哥       652
     意大利      2415
     日本      97746
     法国       3196
     瑞典        231
     美国      57335
     英国       3111
1951 中国大陆     1745
     其他         99
     印度       2287
     墨西哥        73
     意大利      2813
     日本       7370
     法国       3693
     波兰         38
     瑞典       1202
     美国      50073
     英国       6139
1952 中国大陆     4633
     中国香港       47
     俄罗斯       106
     加拿大       116
     墨西哥       142
     意大利      5016
     日本      12827
     法国       5033
     波兰         69
     瑞典        255
     美国      98331
     英国       1623
1953 中国大陆      802
     中国香港      240
     其他        136
     印度         43
     墨西哥       320
     意大利      3486
     日本      44190
     法国      10165
     瑞典       3105
     美国     358624
     西班牙        67
1954 中国大陆     9021
     中国香港      126
     俄罗斯       203
     其他        509
     墨西哥       623
     德国        229
     意大利     14794
     日本      67564
     法国       3048
     瑞典        401
     美国     103790
     英国      22077
1955 中国大陆    77289
     中国香港      816
     丹麦        781
     俄罗斯       332
     其他      67912
     加拿大       351
     印度       1628
     墨西哥       166
     德国         40
     意大利      1987
     日本       6814
     法国      15249
     波兰        604
     瑞典       1492
     美国      48381
     英国       3635
     西班牙       653
1956 中国大陆    18435
     中国香港      594
     俄罗斯      1632
     其他      23909
     印度        946
     意大利     23640
     日本       7898
     法国      36362
     美国      40926
     英国        685
1957 中国大陆     1069
     中国香港      291
     俄罗斯      1263
     其他      23503
     加拿大       302
     印度        129
     意大利     12049
     日本      10608
     法国       1058
     波兰       1690
     瑞典      39664
     美国     211465
     英国      15082
1958 中国大陆    27456
     中国香港      329
     俄罗斯       885
     其他        546
     印度        392
     德国        330
     意大利      3869
     日本      11279
     法国       9964
     波兰       3012
     瑞典        770
     美国      45980
     英国       2968
     荷兰        160
     阿根廷       176
1959 中国大陆    42176
     中国香港     2070
     俄罗斯      3930
     其他        480
     印度        723
     墨西哥       243
     巴西        540
     德国        685
     意大利       838
     日本      10313
     法国      63617
     波兰       1396
     美国      91584
     英国       2214
1960 中国大陆    10421
     中国香港     2573
     俄罗斯       763
     其他       1506
     印度        159
     墨西哥       116
     德国        134
     意大利     12950
     日本      16221
     法国      39642
     波兰        531
     瑞典       7844
     美国      89390
     英国       5691
     韩国       1521
1961 中国大陆   132208
     中国香港      660
     俄罗斯      4769
     其他        312
     加拿大        86
     意大利      7231
     日本      15214
     法国      12879
     波兰        490
     瑞典       2867
     美国     143219
     英国       2985
     西班牙      2048
     韩国         89
1962 中国大陆    77091
     中国香港     1097
     俄罗斯     10151
     其他        248
     加拿大       494
     印度         85
     墨西哥      1246
     巴西        121
     德国        120
     意大利      4990
     日本      33545
     法国      42243
     波兰       5221
     美国      78644
     英国      26684
     荷兰         33
1963 中国台湾      121
     中国大陆    42509
     中国香港     2623
     俄罗斯        65
     其他       1321
     印度        175
     巴西        120
     德国         60
     意大利     26807
     日本       7348
     比利时       173
     法国      13547
     波兰        274
     瑞典       3854
     美国      37016
     英国      33211
     西班牙        92
1964 中国大陆    28290
     中国香港     2819
     丹麦        559
     俄罗斯      2707
     其他       1724
     印度        240
     巴西        233
     德国         40
     意大利     18649
     日本      21454
     法国      22218
     波兰        132
     瑞典        137
     美国      88260
     英国      14151
1965 中国台湾      461
     中国大陆    44280
     中国香港     1456
     俄罗斯      1389
     其他       4048
     加拿大       109
     印度        101
     墨西哥       642
     德国        308
     意大利     13689
     日本       7861
     法国      15172
     波兰        547
     美国     216075
     英国      17776
     西班牙       116
     阿根廷        44
1966 中国台湾       51
     中国大陆      255
     中国香港     6091
     丹麦        362
     俄罗斯      8187
     其他       8170
     加拿大       517
     印度         50
     德国        395
     意大利     42891
     日本      12061
     比利时      5651
     法国     105161
     波兰        622
     瑞典       6248
     美国      18233
     英国      21119
     西班牙       131
1967 中国台湾     4444
     中国香港     5540
     丹麦        175
     俄罗斯      1686
     其他       5138
     巴西        116
     德国        193
     意大利      4830
     日本       8026
     比利时        67
     法国      34715
     波兰        364
     瑞典        791
     美国     137701
     英国      13781
     西班牙       196
1968 中国台湾      178
     中国香港     2606
     俄罗斯      1747
     其他       3206
     墨西哥      2348
     巴西         35
     德国       1741
     意大利     17211
     日本       8056
     比利时      3070
     法国      11997
     波兰        229
     瑞典       1674
     美国     114010
     英国      20162
     西班牙       142
     阿根廷       138
1969 中国台湾      273
     中国香港     8164
     俄罗斯      4567
     其他      15242
     加拿大      1360
     巴西        242
     德国       5201
     意大利      7041
     日本      12561
     法国      10591
     波兰        119
     瑞典        714
     美国      46235
     英国      10326
     西班牙        76
     阿根廷        62
1970 中国台湾     5953
     中国大陆     1552
     中国香港     6203
     丹麦        486
     俄罗斯       571
     其他       6100
     加拿大       239
     印度         39
     墨西哥      2186
     德国       4826
     意大利      8266
     日本       4955
     比利时       210
     法国      10540
     波兰        202
     瑞典        883
     美国      63955
     英国      11256
     西班牙       168
1971 中国台湾      153
     中国大陆      856
     中国香港    18257
     俄罗斯       399
     其他       2024
     加拿大      1170
     印度       3169
     墨西哥      5081
     巴西         91
     德国       2951
     意大利     20587
     日本       4990
     比利时       304
     法国       6554
     波兰        497
     澳大利亚      195
     瑞典        168
     美国      33480
     英国     197068
     荷兰       1513
     西班牙       196
1972 中国台湾      676
     中国大陆      369
     中国香港    37389
     俄罗斯     10800
     其他      11412
     加拿大      1042
     德国       3939
     意大利     38582
     日本      15905
     比利时      1268
     法国      15042
     波兰        631
     瑞典       6231
     美国     320221
     英国       7562
     西班牙      4844
1973 中国台湾     4903
     中国大陆      296
     中国香港    10562
     丹麦       1028
     俄罗斯       353
     其他       2434
     印度        109
     墨西哥      3526
     德国       1017
     意大利      7088
     日本      10794
     法国      14054
     波兰       1013
     瑞典       2439
     美国      93763
     英国       9717
     荷兰       4639
     西班牙      2687
1974 中国台湾      815
     中国大陆    17094
     中国香港    11277
     俄罗斯       979
     其他       7903
     加拿大      3316
     墨西哥       431
     德国       6715
     意大利     21896
     日本      30906
     比利时      2598
     法国      32790
     波兰        265
     澳大利亚      145
     瑞典       2303
     美国     202267
     英国      33604
     荷兰        317
     西班牙       310
1975 中国台湾     2214
     中国大陆      966
     中国香港    10880
     俄罗斯     13565
     其他       2893
     加拿大      1133
     印度         69
     墨西哥        78
     德国       1715
     意大利      4559
     日本       5278
     比利时       994
     法国      44160
     波兰        246
     澳大利亚     4125
     瑞典       1242
     美国     317686
     英国      23601
     荷兰         83
     韩国        170
1976 中国台湾     3189
     中国大陆      310
     中国香港    26347
     俄罗斯       204
     其他       3613
     加拿大      4037
     巴西         40
     德国       2447
     意大利     23086
     日本      20297
     法国      68432
     波兰       1258
     澳大利亚       39
     瑞典        362
     美国     145684
     英国       9938
     西班牙      3081
1977 中国台湾     1761
     中国大陆      144
     中国香港    19878
     俄罗斯     12317
     其他       1471
     加拿大      1274
     印度         57
     德国       5609
     意大利      8232
     日本      20447
     比利时       156
     法国       7772
     波兰        371
     澳大利亚     1285
     瑞典         33
     美国     122633
     英国       6220
     荷兰        908
1978 中国台湾     2618
     中国大陆     1824
     中国香港    57300
     丹麦        650
     俄罗斯      1114
     其他       1568
     墨西哥        47
     德国       2159
     意大利      7596
     日本       3456
     比利时       356
     法国       6832
     澳大利亚      132
     瑞典       8154
     美国      58114
     英国      49214
     西班牙       232
1979 中国台湾     7887
     中国大陆    74604
     中国香港    20632
     俄罗斯      9847
     其他       3374
     加拿大       894
     印度        258
     德国      27744
     意大利     16747
     日本      24880
     比利时      1625
     法国      27229
     波兰       2109
     澳大利亚     6394
     美国     118110
     英国      83993
     西班牙       120
1980 中国台湾     2200
     中国大陆    80370
     中国香港    28410
     丹麦        234
     俄罗斯      8291
     其他      82661
     加拿大      1276
     德国        298
     意大利      6266
     日本       8474
     法国      53374
     波兰        922
     澳大利亚      837
     瑞典        497
     美国     161143
     英国     103208
     荷兰        144
     西班牙       716
1981 中国台湾     4143
     中国大陆   201269
     中国香港    27940
     丹麦         52
     俄罗斯      1000
     其他      20330
     加拿大      9566
     巴西        197
     德国       6117
     意大利      1873
     日本      13963
     法国      19568
     波兰      11287
     澳大利亚     5933
     瑞典        189
     美国      78512
     英国      38357
     荷兰         47
     西班牙       397
     韩国        143
1982 中国台湾     6199
     中国大陆    97271
     中国香港    52765
     俄罗斯      4098
     其他      16856
     加拿大       468
     印度         61
     墨西哥       141
     巴西        205
     德国       1392
     意大利      1874
     日本      11852
     法国      21842
     波兰        199
     澳大利亚      630
     瑞典        132
     美国     282899
     英国      70225
     西班牙       857
1983 中国台湾    22919
     中国大陆    81808
     中国香港   116754
     丹麦       1142
     俄罗斯      9536
     其他       5682
     加拿大      3190
     印度         98
     墨西哥       107
     德国        133
     意大利      2605
     日本      25769
     法国      16663
     澳大利亚      178
     美国      99431
     英国      34052
     荷兰       2631
     西班牙      4212
1984 中国台湾     9558
     中国大陆    28751
     中国香港   103660
     丹麦       1023
     俄罗斯       921
     其他       5150
     加拿大      1719
     德国       1625
     意大利    141974
     日本     159847
     法国       6343
     波兰        792
     澳大利亚      511
     瑞典        244
     美国     266820
     英国      47220
     荷兰       6681
     西班牙      1190
     阿根廷        25
     韩国         95
1985 中国台湾    18207
     中国大陆    15897
     中国香港   113874
     俄罗斯      6106
     其他       6442
     加拿大      4453
     墨西哥        57
     巴西         52
     德国        279
     意大利      2773
     日本      56537
     法国      13418
     波兰       3422
     澳大利亚     3829
     瑞典       9007
     美国     206116
     英国      48178
     荷兰        194
     西班牙       233
     阿根廷       627
     韩国         78
1986 中国台湾    12628
     中国大陆    60850
     中国香港   188439
     俄罗斯       858
     其他       3356
     加拿大      3704
     德国       3944
     意大利      1314
     日本     286934
     法国      44606
     澳大利亚     1791
     瑞典       3030
     美国     281374
     英国      19846
     荷兰        427
     西班牙      2355
     阿根廷       871
     韩国        109
1987 中国台湾    32262
     中国大陆   107166
     中国香港   403003
     丹麦       4663
     俄罗斯      3785
     其他      10440
     加拿大      4684
     印度        242
     墨西哥        49
     德国      30556
     意大利    119566
     日本      57256
     比利时       736
     法国      10496
     波兰       3861
     澳大利亚      920
     瑞典        115
     美国     182202
     英国      96401
     荷兰        101
     西班牙      3892
     韩国        774
1988 中国台湾    32186
     中国大陆    72474
     中国香港   313086
     丹麦        239
     俄罗斯      2257
     其他       6105
     加拿大     12072
     印度        104
     德国         50
     意大利    263739
     日本     567900
     比利时        64
     法国     155884
     波兰      16555
     澳大利亚     6647
     瑞典        249
     美国     408244
     英国      12110
     荷兰       2920
     西班牙      3604
     阿根廷       400
1989 中国台湾    40547
     中国大陆    22764
     中国香港   254258
     俄罗斯       996
     其他      60110
     加拿大      2080
     墨西哥      2816
     德国        878
     意大利      1848
     日本     177434
     比利时      1548
     法国      20440
     波兰        937
     澳大利亚     1449
     美国     564234
     英国      23858
     西班牙       115
     阿根廷        88
     韩国        406
1990 中国台湾    10338
     中国大陆    60312
     中国香港   574916
     俄罗斯      1593
     其他       9046
     加拿大       522
     巴西         68
     德国        734
     意大利      8108
     日本      29254
     法国      37854
     波兰         47
     澳大利亚     4937
     美国    1179900
     英国      16765
     荷兰         30
     西班牙     16920
     韩国        132
1991 中国台湾   120202
     中国大陆   109925
     中国香港   693666
     丹麦       1765
     俄罗斯       121
     其他       7973
     加拿大      7273
     墨西哥      1013
     德国       1611
     意大利      5582
     日本     100469
     比利时      2776
     法国     131211
     波兰         92
     澳大利亚     1010
     美国     714925
     英国      15067
     荷兰        184
     西班牙      6040
     韩国        281
1992 中国台湾    37466
     中国大陆   116750
     中国香港   954938
     丹麦        348
     俄罗斯      1931
     其他      20600
     加拿大      1330
     墨西哥      9324
     德国        805
     意大利      2483
     日本     102400
     比利时      4672
     法国     125613
     波兰        481
     澳大利亚     2223
     瑞典        323
     美国     941074
     英国      44844
     荷兰       7031
     西班牙      9771
     阿根廷      1836
     韩国        225
1993 中国台湾   105238
     中国大陆   539290
     中国香港  1374596
     丹麦         72
     俄罗斯       620
     其他      49082
     加拿大      1859
     印度         31
     墨西哥       814
     德国       9094
     意大利       798
     日本      79928
     比利时      3246
     法国     133200
     澳大利亚    62792
     瑞典         46
     美国    1177220
     英国      33227
     西班牙      7441
     韩国       1338
1994 中国台湾   162341
     中国大陆   466107
     中国香港  1300511
     丹麦        803
     俄罗斯     19390
     其他      24910
     加拿大      3809
     印度        101
     德国       6735
     意大利     13572
     日本      92129
     比利时       379
     法国     808975
     波兰        759

通过将“投票人数”和“评分”列进行对应分组，对“产地”实现数据聚合和总结

In [65]:
pd.pivot_table(df,index=['产地'],values=['投票人数','评分'],aggfunc=[np.sum,np.mean])

            sum                   mean
           投票人数       评分          投票人数        评分
产地
中国台湾    5237466   4367.2   8474.864078  7.066667
中国大陆   41435313  23058.0  10898.293793  6.064703
中国香港   23285389  18457.7   8167.446159  6.474114
丹麦       394784   1434.7   1993.858586  7.245960
俄罗斯      486127   3603.5   1019.134172  7.554507
其他      3054119  13895.9   1590.686979  7.237448
加拿大     1384765   4868.4   1915.304288  6.733610
印度      1146271   2453.4   3210.843137  6.872269
墨西哥      139613    843.4   1173.218487  7.087395
巴西       357136    733.5   3536.000000  7.262376
德国      2680983   7428.4   2597.851744  7.198062
意大利     2502215   5377.3   3340.740988  7.179306
日本     18000667  36339.3   3563.782815  7.194476
比利时      170987   1003.3   1230.122302  7.217986
法国     10213966  20384.7   3627.118608  7.238885
波兰       159577   1347.0    881.640884  7.441989
泰国      1564881   1796.1   5322.724490  6.109184
澳大利亚    1415713   2093.4   4719.043333  6.978000
瑞典       290077   1423.3   1510.817708  7.413021
美国    101806216  83209.5   8499.433628  6.946861
英国     13249562  20789.4   4797.089790  7.526937
荷兰       144836   1114.5    934.425806  7.190323
西班牙     1486733   3139.9   3326.024609  7.024385
阿根廷      258271    843.7   2226.474138  7.273276
韩国      8761080   8596.4   6484.885270  6.362990

##### 非数值处理 fill_value

非数值（NaN）难以处理，如果想移除他们，可以使用 fill_value 将其设置为0

In [103]:
pd.pivot_table(df,index=['产地'],aggfunc=[np.sum,np.mean],fill_value=0)

           sum                                           mean                \
            年代       投票人数       时长            评分           年代          投票人数
产地
中国台湾   1235388    5237466    53925   4367.200000  1999.009709   8474.864078
中国大陆   7621488   41435313   309608  23058.000000  2004.599684  10898.293793
中国香港   5676627   23285389   252431  18457.700000  1991.100316   8167.446159
丹麦      395820     394784    17444   1434.700000  1999.090909   1993.858586
俄罗斯    3006734    3167110   140761  11031.900000  1992.534129   2098.813784
其他     3837588    3054119   167168  13895.900000  1998.743750   1590.686979
加拿大    1447780    1384765    57919   4868.400000  2002.461964   1915.304288
印度      716133    1146271    43203   2453.400000  2005.974790   3210.843137
墨西哥     237145     139613    10929    843.400000  1992.815126   1173.218487
巴西      201987     357136     8869    733.500000  1999.871287   3536.000000
意大利    1487142    2502215    77902   5377.300000  1985.503338   3340.740988
日本    10101505   18000667   427863  36339.300000  1999.902000   3563.782815
比利时     277930     170987    11447   1003.300000  1999.496403   1230.122302
法国     5608811   10213966   253169  20384.700000  1991.765270   3627.118608
波兰      359652     159577    14613   1347.000000  1987.027624    881.640884
泰国      590684    1564881    26002   1796.100000  2009.129252   5322.724490
澳大利亚    600896    1415713    25549   2093.400000  2002.986667   4719.043333
瑞典      381491     290077    17898   1423.300000  1986.932292   1510.817708
美国    23892986  101929672  1070310  83216.435704  1994.572669   8509.030136
英国     5514959   13249562   244005  20789.400000  1996.726647   4797.089790
荷兰      310199     144836    11685   1114.500000  2001.283871    934.425806
西班牙     894710    1486733    40455   3139.900000  2001.588367   3326.024609
阿根廷     232468     258271    10638    843.700000  2004.034483   2226.474138
韩国     2712969    8761080   134734   8596.400000  2008.119171   6484.885270


              时长        评分
产地
中国台湾   87.257282  7.066667
中国大陆   81.432930  6.064703
中国香港   88.541214  6.474114
丹麦     88.101010  7.245960
俄罗斯    93.280981  7.310736
其他     87.066667  7.237448
加拿大    80.109267  6.733610
印度    121.016807  6.872269
墨西哥    91.840336  7.087395
巴西     87.811881  7.262376
意大利   104.008011  7.179306
日本     84.708573  7.194476
比利时    82.352518  7.217986
法国     89.903764  7.238885
波兰     80.734807  7.441989
泰国     88.442177  6.109184
澳大利亚   85.163333  6.978000
瑞典     93.218750  7.413021
美国     89.348861  6.946860
英国     88.343592  7.526937
荷兰     75.387097  7.190323
西班牙    90.503356  7.024385
阿根廷    91.706897  7.273276
韩国     99.729090  6.362990

##### 计算总合数据 margins=True

In [104]:
pd.pivot_table(df,index=['产地'],aggfunc=[np.sum,np.mean],fill_value=0,margins=True)

           sum                                            mean                \
            年代       投票人数       时长             评分           年代          投票人数
产地
中国台湾   1235388    5237466    53925    4367.200000  1999.009709   8474.864078
中国大陆   7621488   41435313   309608   23058.000000  2004.599684  10898.293793
中国香港   5676627   23285389   252431   18457.700000  1991.100316   8167.446159
丹麦      395820     394784    17444    1434.700000  1999.090909   1993.858586
俄罗斯    3006734    3167110   140761   11031.900000  1992.534129   2098.813784
其他     3837588    3054119   167168   13895.900000  1998.743750   1590.686979
加拿大    1447780    1384765    57919    4868.400000  2002.461964   1915.304288
印度      716133    1146271    43203    2453.400000  2005.974790   3210.843137
墨西哥     237145     139613    10929     843.400000  1992.815126   1173.218487
巴西      201987     357136     8869     733.500000  1999.871287   3536.000000
意大利    1487142    2502215    77902    5377.300000  1985.503338   3340.740988
日本    10101505   18000667   427863   36339.300000  1999.902000   3563.782815
比利时     277930     170987    11447    1003.300000  1999.496403   1230.122302
法国     5608811   10213966   253169   20384.700000  1991.765270   3627.118608
波兰      359652     159577    14613    1347.000000  1987.027624    881.640884
泰国      590684    1564881    26002    1796.100000  2009.129252   5322.724490
澳大利亚    600896    1415713    25549    2093.400000  2002.986667   4719.043333
瑞典      381491     290077    17898    1423.300000  1986.932292   1510.817708
美国    23892986  101929672  1070310   83216.435704  1994.572669   8509.030136
英国     5514959   13249562   244005   20789.400000  1996.726647   4797.089790
荷兰      310199     144836    11685    1114.500000  2001.283871    934.425806
西班牙     894710    1486733    40455    3139.900000  2001.588367   3326.024609
阿根廷     232468     258271    10638     843.700000  2004.034483   2226.474138
韩国     2712969    8761080   134734    8596.400000  2008.119171   6484.885270
All   77337135  239749731  3428380  268585.635704  1996.982338   6190.764350


              时长        评分
产地
中国台湾   87.257282  7.066667
中国大陆   81.432930  6.064703
中国香港   88.541214  6.474114
丹麦     88.101010  7.245960
俄罗斯    93.280981  7.310736
其他     87.066667  7.237448
加拿大    80.109267  6.733610
印度    121.016807  6.872269
墨西哥    91.840336  7.087395
巴西     87.811881  7.262376
意大利   104.008011  7.179306
日本     84.708573  7.194476
比利时    82.352518  7.217986
法国     89.903764  7.238885
波兰     80.734807  7.441989
泰国     88.442177  6.109184
澳大利亚   85.163333  6.978000
瑞典     93.218750  7.413021
美国     89.348861  6.946860
英国     88.343592  7.526937
荷兰     75.387097  7.190323
西班牙    90.503356  7.024385
阿根廷    91.706897  7.273276
韩国     99.729090  6.362990
All    88.526868  6.935359

##### 对不同值执行不同函数

可以向aggfunc传递一个字典。不过，这样做有一个副作用，那就是必须将标签做的更加简洁才性。

对各个产地的投票人数求和，对评分求均值

In [66]:
pd.pivot_table(df,index=['产地'],values=['投票人数','评分'],aggfunc={'投票人数':np.sum,'评分':np.mean},fill_value=0)

           投票人数        评分
产地
中国台湾    5237466  7.066667
中国大陆   41435313  6.064703
中国香港   23285389  6.474114
丹麦       394784  7.245960
俄罗斯      486127  7.554507
其他      3054119  7.237448
加拿大     1384765  6.733610
印度      1146271  6.872269
墨西哥      139613  7.087395
巴西       357136  7.262376
德国      2680983  7.198062
意大利     2502215  7.179306
日本     18000667  7.194476
比利时      170987  7.217986
法国     10213966  7.238885
波兰       159577  7.441989
泰国      1564881  6.109184
澳大利亚    1415713  6.978000
瑞典       290077  7.413021
美国    101806216  6.946861
英国     13249562  7.526937
荷兰       144836  7.190323
西班牙     1486733  7.024385
阿根廷      258271  7.273276
韩国      8761080  6.362990

对各个年份的投票人数求和，对评分求均值

In [67]:
table=pd.pivot_table(df,index=['年代'],values=['投票人数','评分'],aggfunc={'投票人数':np.sum,'评分':np.mean},fill_value=0)
table

          投票人数        评分
年代
1888       776  7.950000
1890        51  4.800000
1892       176  7.500000
1894       338  6.633333
1895      7679  7.575000
1896      7874  7.037500
1897       201  6.633333
1898      1157  7.450000
1899       142  6.900000
1900      1227  7.228571
1901       658  7.250000
1902     11605  7.483333
1903      4730  6.968750
1904      1567  7.212500
1905      1663  6.820000
1906      1329  7.342857
1907      1068  7.020000
1908      1553  7.150000
1909       293  7.560000
1910       526  6.940000
1911       960  7.375000
1912       761  7.920000
1913       529  6.862500
1914      2728  6.473077
1915      6298  7.260000
1916      7364  7.758333
1917      1493  7.075000
1918      4285  7.200000
1919      3597  7.490000
1920      8911  7.492857
1921     16056  7.750000
1922     16876  7.804545
1923      7668  7.883333
1924     10410  8.053571
1925     27607  7.788000
1926     10203  7.773913
1927     20163  7.751724
1928     16193  7.945000
1929     25919  7.440000
1930     13877  7.360000
1931     61684  7.483333
1932     22203  7.294595
1933     36486  7.430000
1934     39601  7.519608
1935     40834  7.515217
1936     87928  7.635000
1937     77431  7.575510
1938     20976  7.736842
1939    289681  7.520408
1940    216401  7.571795
1941     72982  7.427660
1942    138211  7.554717
1943     42342  7.615789
1944     54398  7.538889
1945     48462  7.673469
1946     61033  7.606780
1947     32955  7.453333
1948    103226  7.657471
1949     57110  7.646067
1950    169862  7.655263
1951     75532  7.636709
1952    128198  7.743678
1953    421178  7.567045
1954    222385  7.702941
1955    228130  7.580000
1956    155027  7.600000
1957    318173  7.652336
1958    108116  7.536885
1959    220809  7.571875
1960    189462  7.569466
1961    325057  7.744118
1962    282013  7.704895
1963    169316  7.536364
1964    201613  7.523077
1965    324074  7.576074
1966    236195  7.518994
1967    217763  7.484659
1968    188550  7.317442
1969    122774  7.370048
1970    128590  7.291053
1971    299703  7.155708
1972    475913  7.268116
1973    170422  7.250235
1974    375931  7.062332
1975    435657  7.071429
1976    312364  7.107725
1977    210568  7.148182
1978    201366  7.096517
1979    426447  7.296035
1980    539321  7.186607
1981    440883  7.157299
1982    569966  7.297368
1983    426910  7.310108
1984    784149  7.375170
1985    509779  7.278505
1986    916436  7.256790
1987   1073170  7.284548
1988   1876889  7.265729
1989   1176806  7.210687
1990   1951476  7.149109
1991   1921186  7.154634
1992   2386468  7.223678
1993   3579932  7.195692
1994   5670752  7.262348
1995   3976844  7.289366
1996   2634572  7.258801
1997   4426995  7.330168
1998   4288143  7.238302
1999   4460656  7.188000
2000   4318580  7.134063
2001   7029519  7.110145
2002   5897334  7.069778
2003   7505258  7.137750
2004   9746963  7.031366
2005   8217218  7.030008
2006  11026565  6.914719
2007  10700316  6.875102
2008  13252207  6.910647
2009  16229871  6.750000
2010  18061067  6.770361
2011  16351964  6.577010
2012  14463052  6.458374
2013  15215050  6.392604
2014  14573872  6.259777
2015  12483522  6.141960
2016   1851413  5.868217

##### 透视表过滤

In [110]:
type(table)

pandas.core.frame.DataFrame

In [111]:
table[:5]

      投票人数        评分
年代
1888   776  7.950000
1890    51  4.800000
1892   176  7.500000
1894   338  6.633333
1895  7679  7.575000

1994年被誉为电影史上伟大的一年，但是通过数据我们可以发现，1994年的平均分并不是很高。1924年的电影平均分最高。

In [112]:
table[table.index==1994]

         投票人数        评分
年代
1994  5670752  7.262348

In [115]:
table.sort_values('评分',ascending=False)[:10]

       投票人数        评分
年代
1924  10410  8.053571
1888    776  7.950000
1928  16193  7.945000
1912    761  7.920000
1923   7668  7.883333
1922  16876  7.804545
1925  27607  7.788000
1926  10203  7.773913
1916   7364  7.758333
1927  20163  7.751724

##### 按照多个索引来进行汇总

In [118]:
pd.pivot_table(df,index=['产地','年代'],values=['投票人数','评分'],aggfunc={'投票人数':np.sum,'评分':np.mean},fill_value=0)

              投票人数        评分
产地   年代
中国台湾 1963      121  6.400000
     1965      461  6.800000
     1966       51  7.900000
     1967     4444  8.000000
     1968      178  7.400000
...            ...       ...
韩国   2012   610829  6.064151
     2013  1130983  6.098198
     2014   453152  5.650833
     2015   349808  5.423853
     2016    34797  5.730000

[1511 rows x 2 columns]